version: "3.9"
services:
  constacts-frontend:
    image: frontend
    ports:
      - '80:8080'
    networks:
      - nesjs-network

  constacts-api:
    image: api
    ports:
      - '3333:3333'
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGODB_DATABASE="contactdb"
    networks:
      - nesjs-network
    volumes:
      - mongo-data:/data/contactdb
    restart: always

networks:
  nesjs-network:
    driver: bridge

volumes:
  mongo-data: